@vps = http://localhost:3002
@chave = dev-somente-local-dev-somente-local

### Sincronização
POST {{vps}}/api/estacao/sincronizacao
Content-Type: application/json
Authorization: {{chave}}

{ "call": "getSincronizacao" }
